-- CreateTable
CREATE TABLE "TB_USUARIO" (
    "ID_USUARIO" TEXT NOT NULL PRIMARY KEY,
    "ATIVO" BOOLEAN NOT NULL DEFAULT false,
    "NOME_COMPLETO" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "TELEFONE" TEXT NOT NULL,
    "CPF" TEXT NOT NULL,
    "CARGO" TEXT NOT NULL,
    "CARGO_AREA" TEXT NOT NULL,
    "SENHA" TEXT NOT NULL,
    "DATA_CRIACAO" DATETIME NOT NULL,
    "DATA_ATUALIZACAO" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "TB_PERMISSAO" (
    "ID_PERMISSAO" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "DESCRICAO_PERMISSAO" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "TB_PERMISSAO_USUARIO" (
    "ID_PERMISSAO_USUARIO" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "FK_ID_USUARIO" TEXT NOT NULL,
    "FK_ID_PERMISSAO" INTEGER NOT NULL,
    CONSTRAINT "TB_PERMISSAO_USUARIO_FK_ID_USUARIO_fkey" FOREIGN KEY ("FK_ID_USUARIO") REFERENCES "TB_USUARIO" ("ID_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "TB_PERMISSAO_USUARIO_FK_ID_PERMISSAO_fkey" FOREIGN KEY ("FK_ID_PERMISSAO") REFERENCES "TB_PERMISSAO" ("ID_PERMISSAO") ON DELETE RESTRICT ON UPDATE CASCADE
);
