CREATE DATABASE DB_CONTROLE_ACESSO;
GO

USE DB_CONTROLE_ACESSO;
GO

--DROP DATABASE DB_CONTROLE_ACESSO;

CREATE TABLE TB_USUARIO(
  ID_USUARIO UNIQUEIDENTIFIER PRIMARY KEY,
  ATIVO BIT DEFAULT 0 NOT NULL,
  NOME_COMPLETO VARCHAR(80) UNIQUE NOT NULL,
  EMAIL VARCHAR(60) UNIQUE NOT NULL,
  TELEFONE CHAR(11) NOT NULL,
  CPF CHAR(11) NOT NULL,
  CARGO VARCHAR(40) NOT NULL,
  CARGO_AREA VARCHAR (60),
  SENHA VARCHAR(200) NOT NULL,
  DATA_CRIACAO DATETIME NOT NULL,
  DATA_ATUALIZACAO DATETIME NOT NULL,
)
GO

CREATE TABLE TB_PERMISSAO(
  ID_PERMISSAO INT IDENTITY PRIMARY KEY,
  DESCRICAO_PERMISSAO VARCHAR(40) UNIQUE NOT NULL
)
GO

CREATE TABLE TB_PERMISSAO_USUARIO(
  ID_PERMISSAO_USUARIO INT IDENTITY PRIMARY KEY,
  FK_ID_USUARIO UNIQUEIDENTIFIER NOT NULL,
  FK_ID_PERMISSAO INT NOT NULL,
  FOREIGN KEY(FK_ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO),
  FOREIGN KEY(FK_ID_PERMISSAO) REFERENCES TB_PERMISSAO(ID_PERMISSAO),
)
GO

